name: 'Kinda Contribute'
description: 'Simulates your contribution'
author: 'Th3Un1q3'
inputs:
  max-commits:
    description: 'How many commits to make per run'
    required: false
    default: '5'
  exact-commits:
    description: 'How many commits to make per run'
    required: false
  include-push:
    description: 'Whether to push to the target branch'
    required: false
    default: 'true'

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      id: define-commits-to-make
      with:
        script: |
            try {
              const exactCommits = Number.parseInt("${{ inputs.exact-commits }}");
              const maxCommits = Number.parseInt("${{ inputs.max-commits }}");
              const commitsNumber = exactCommits || Math.round(Math.random() * (maxCommits - 1) + 1);
              console.log({commitsNumber});
              return {
                commitsNumber,
              }
            } catch(error) {
              return {
                commitsNumber: "${{ inputs.max-commits }}",
              }
            }
    - name: Get result
      run: echo "${{ fromJson(steps.define-commits-to-make.outputs.result).commitsNumber }}"
      shell: bash

    - run: generate-activity.sh -c ${{ fromJson(steps.define-commits-to-make.outputs.result).commitsNumber }}
      shell: bash

    - run: git push
      shell: bash
