name: 'Test Contribution'
on:
  workflow_dispatch:
    inputs:
      max-commits:
        description: 'Maximum number of commits to make'
        required: false
        default: '5'
      exact-commits:
        description: 'Exact number of commits to make(overrides max-commits)'
        required: false
      target-branch-ref:
        description: 'Target branch ref to push to(e.g. origin/main)'
        required: false

jobs:
  run:
    name: Test In Workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ inputs.target-branch-ref }}"
          # It's required to use your personal access token
          # in order to make it look like it's your activity.
          # The token must be enabled for the private repo scopes.
          # [Action Docs](https://github.com/actions/checkout#usage)
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - uses: 'Th3Un1q3/kinda-contribute@main'
        with:
          max-commits: ${{ inputs.max-commits }}
          exact-commits: ${{ inputs.exact-commits }}
          include-push: false
